### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F09-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F09-1/main#320]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: ] (:exclamation:)
   * [x] All issues in this milestone are closed(:exclamation:)
   * [x] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @mudaafi for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-1/main/pull/307 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/306 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/294 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/293 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/288 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/280 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/261 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/251 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/245 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/239 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/230 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/223 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/210 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/304 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/291 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/244 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/238 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/233 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/223 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/209 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/116 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/115 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/114 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/113 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/53 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @sallysohyun for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-1/main/issues/304 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @priyan-coder for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-1/main/pull/305 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/297 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/283 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/273 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/233 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/224 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/221 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/216 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/212 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/118 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/112 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/98 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/97 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/304 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/254 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/253 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/239 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/231 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/215 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/110 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/92 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/91 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ajeyashok for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-1/main/issues/304 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/301 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/265 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/233 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @araavinds for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-1/main/pull/275 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/269 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/304 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/266 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/263 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/262 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/252 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/246 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/241 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/214 https://github.com/AY1920S1-CS2113T-F09-1/main/pull/210 https://github.com/AY1920S1-CS2113T-F09-1/main/issues/95 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @Rishav1

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
